[package]
name = "_"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.21.3"
js-sys = "0.3.64"
vbyte = "0.1.0"
wasm-bindgen = "0.2.87"
z85 = "3.0.5"

[profile.release]
opt-level = 's'
lto = true
